### ISSUE TITLE
Go for NodeJS

### ISSUE THREAD

**Issue by AmrAbdulrahman** [lordadamson/gitbaby#1]
Dude, although it looks more geeky to write scripts in bash, but from my POV, for development and pull-requests, and open source contributions sake, I'd suggest that you do it in NodeJS, code will be much more readable, structured and so on.
Anyway, I liked the idea so much!

**Comment by lordadamson** [comment]
Hi buddy :D
I'm sorry but how is NodeJS related?

**Comment by AmrAbdulrahman** [comment]
You can do warever scripting you want using NodeJS.
Check out exec() and execSync() node APIs, it enables you to run shell commands from inside NodeJS script, this will help you writing your "baby" scripts in JS, and make use of JS as a programming language.

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by lordadamson** [comment]
while this sounds really cool. I'll have to disagree for several reasons.
* NodeJS needs to be installed on the user's machine. So python sounds like a better option.
* even though there is that trend among devs and sysadmins that bash shouldn't ever be used because it's unreadable and stuff. While I agree that bash is sometimes just stupid. sometimes it's really an overkill to write scripts in other languages when all you need is just a mix of simple commands piped together.

**Comment by AmrAbdulrahman** [comment]
Exactly!
I totally agree on the first point, and partially agree on the second one.
My point is, at this point of time, you'll try to add more and more features, and make your script more helpful, that won't be so easy using bash, while it can be very easy and much more stable in Python/Node. So, it's a strategic decision, If you think that source code will remain quite small, then just throw away my advice.

**Comment by lordadamson** [comment]
well yeah I doubt the script will get much bigger :D it's called baby for a reason.

**Comment by AmrAbdulrahman** [comment]
aaaha, i thought you meant "babe" my bad : P :D
